### PR TITLE
Releases watchmaker version 0.27.4

### PR DESCRIPTION
**Pull request by eemperor**
Changes since 0.27.3: https://github.com/plus3it/watchmaker/compare/0.27.3...main

### CODE REVIEW

**Comment by eemperor** [comment]
go codebuild go

**Comment by eemperor** [comment]
go codebuild go

**Comment by lorengordon** [comment]
@eemperor Would you mind rebasing from updated upstream/main? Some dependency PRs got merged this morning and just want to make sure the build is clean...

**Comment by eemperor** [comment]
go codebuild go

**Review by lorengordon — APPROVED** [review]

**Pull request merged**
