### PR TITLE
Releases watchmaker version 0.28.5

### PR DESCRIPTION
**Pull request by eemperor**
Changes since 0.28.4: https://github.com/plus3it/watchmaker/compare/0.28.4...main

### CODE REVIEW

**Comment by eemperor** [comment]
go codebuild go

**Review by ferricoxide — APPROVED** [review]
Functionality-changes seem to be in the externalized content (watchmaker-called formulae), so, not much to actually review. Approving pending successful completion of CI tests.

**Comment by eemperor** [comment]
go codebuild go

**Review by ferricoxide — APPROVED** [review]
This space intentionally left blank

**Pull request merged**
