### PR TITLE
Releases watchmaker 0.10.0

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by eemperor** [comment]
Any concerns with the codecov test fails?

**Comment by YakDriver** [comment]
The travis codecov tests all passed fine. IMHO these patch/project-level codecov percentages are 1) aspirational not necessarily show stoppers, and 2) difficult to achieve where a test harness is not available (i.e., `travis.yml` vs. python code).

**Comment by YakDriver** [comment]
go codebuild go

**Comment by lorengordon** [comment]
The codecov integration is purely informational. We don't have much in the way of unit tests, which drive coverage. Since we don't have the unit tests anyway, we haven't bothered figuring out what codecov is trying to tell us or managing the codecov config to better reflect what we care about.

**Comment by eemperor** [comment]
Thanks for the explanations.  I have only done a cursory look at covecov so I wasn't what the errors really meant.

**Pull request merged**
