### PR TITLE
Prepares watchmaker 0.21.2 release

### PR DESCRIPTION
**Pull request by eemperor**

### CODE REVIEW

**Comment by eemperor** [comment]
go codebuild go

**Review by lorengordon — CHANGES_REQUESTED** [review]
I'd like to update the [default watchmaker config](https://github.com/plus3it/watchmaker/blob/develop/src/watchmaker/static/config.yaml#L1) in this release also, to use salt 3001.1.

**Comment by eemperor** [comment]
go codebuild go

**Comment by eemperor** [comment]
@lorengordon What do you think about releasing without updating default configs to use 3001.1?

**Comment by lorengordon** [comment]
Yeah that's fine, considering the annoying log flooding in 3001.1...

**Comment by eemperor** [comment]
go codebuild go

**Comment by eemperor** [comment]
go codebuild go

**Review by lorengordon — APPROVED** [review]
🚢

**Pull request merged**
