### PR TITLE
Prepares watchmaker 0.19.0 release

### PR DESCRIPTION
**Pull request by spavuluri**

### CODE REVIEW

**Comment by spavuluri** [comment]
go codebuild go

**Comment by YakDriver** [comment]
I thought we were going to include the pip stuff.

**Comment by confusdcodr** [comment]
Is this actually a backwards incompatible change?

**Comment by spavuluri** [comment]
@confusdcodr No, it's backwards compatible. The SaltWorker arg provides new functionality though.
@YakDriver hmm, not sure.

**Comment by eemperor** [comment]
@YakDriver We can do another release when the pip stuff is done.

**Pull request merged**
