### PR TITLE
Replaces use of `__file__` and `__path__` with importlib metadata and resources

### PR DESCRIPTION
**Pull request by lorengordon**
Turns out the `__file__` attribute is not guaranteed to exist, and causes problems for a number of packaging solutions. See also: https://github.com/indygreg/PyOxidizer/issues/69

### CODE REVIEW

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Review by dwc0011 — APPROVED** [review]

**Pull request merged**
