### PR TITLE
Force inclusion of OpenSSL libraries and hash-files

### LINKED ISSUE #2929: [BUG] Watchmaker Standalone Binary Fails On EL8+FIPS
**Problem Description:**

When executing the watchmaker standalone binaries on EL8-based distros that have had FIPS-mode enabled, execution fails with:

~~~
crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
Aborted (core dumped)
~~~

**Suggested Fix:**

Update the `ci/pyinstaller/hook-watchmaker.py` to force the inclusion of the OpenSSL `libcrypto` and `libssl` libraries and associated `.hmac` files.

### PR DESCRIPTION
**Pull request by ferricoxide**
Use wildcards for libcrypto and libssl DSOs and .hmac files

Closes #2929

### CODE REVIEW

**Comment by ferricoxide** [comment]
go codebuild go

**Comment by ferricoxide** [comment]
go codebuild go

**Comment by ferricoxide** [comment]
go codebuild go

**Review by lorengordon — APPROVED** [review]
🚀

**Pull request merged**
