### PR TITLE
New PowerShell UserData

### PR DESCRIPTION
**Pull request by KevinPlus3**
Adding PowerShell userdata script for Windows AMIs that will install Python using an MSI, upgrade pip and easy_install WatchMaker egg that is stored in S3 bucket, dicelab_eggs.

---
This change is [Reviewable](https://reviewable.io/reviews/plus3it/watchmaker/12)

### CODE REVIEW

**Comment by lorengordon** [comment]
Mind squashing the duplicate commit messages?

**Comment by KevinPlus3** [comment]
I was able to squash the commits locally but I am unable to push it up to remote branch. Something about fast-forwards.  Perhaps next time around I can be on the look-out to make sure to squash commits before pushing them up.

**Comment by KevinPlus3** [comment]
Did a git push --force.  Now shows up as 4 commits.

**Comment by lorengordon** [comment]
This looks correct. There were 5 commits previously, now there are 4. The commit _message_ on the 4th commit is a little odd, though not unusual when squashing. You could use `git commit --amend` if you wanted to cleanup the message.

**Comment by lorengordon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[watchmaker/static/shell/bootstrappers/linux-image-bootstrap.py, line 1 \[r1\]](https://reviewable.io:443/reviews/plus3it/watchmaker/12#-KJaeip5mv7w6wg6SgE9:-KJaeip5mv7w6wg6SgEA:1224096985) ([raw file](https://github.com/plus3it/watchmaker/blob/0075a34126491b863c9e0ebdf9a85ff6b45936c7/watchmaker/static/shell/bootstrappers/linux-image-bootstrap.py#L1)):*
> ```Python
> #!/usr/bin/env bash
> ```

This is a .py file, should this be `#!/usr/bin/env python`?

---

*[watchmaker/static/shell/bootstrappers/linux-image-bootstrap.py, line 3 \[r1\]](https://reviewable.io:443/reviews/plus3it/watchmaker/12#-KJaeyHayDnv7el8VKkw:-KJaeyHb2Gvg03SS60aJ:-525273563) ([raw file](https://github.com/plus3it/watchmaker/blob/0075a34126491b863c9e0ebdf9a85ff6b45936c7/watchmaker/static/shell/bootstrappers/linux-image-bootstrap.py#L3)):*
> ```Python
> #!/usr/bin/env bash
> 
> # This will be the userdata for Linux EC2 images to run SystemPrep via WatchMaker.
> ```

Can you add a newline here? That little red mark at the end of the line is Github saying there is no newline character.

---

*[watchmaker/static/shell/bootstrappers/windows-image-bootstrap.ps1, line 1 \[r1\]](https://reviewable.io:443/reviews/plus3it/watchmaker/12#-KJafHWYUOV0BEtS8uGV:-KJafHWYUOV0BEtS8uGW:-896274393) ([raw file](https://github.com/plus3it/watchmaker/blob/0075a34126491b863c9e0ebdf9a85ff6b45936c7/watchmaker/static/shell/bootstrappers/windows-image-bootstrap.ps1#L1)):*
> ```PowerShell
> <powershell>
> ```

We should have a discussion on whether to call this a .ps1 file, or .ps1.txt. The xml <powershell> tags make it invalid powershell...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plus3it/watchmaker/12)*

**Comment by KevinPlus3** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[watchmaker/static/shell/bootstrappers/windows-image-bootstrap.ps1, line 1 \[r1\]](https://reviewable.io:443/reviews/plus3it/watchmaker/12#-KJafHWYUOV0BEtS8uGV:-KJagOzK6d7eJx9jUFNf:-1135573122) ([raw file](https://github.com/plus3it/watchmaker/blob/0075a34126491b863c9e0ebdf9a85ff6b45936c7/watchmaker/static/shell/bootstrappers/windows-image-bootstrap.ps1#L1)):*
<details><summary><i>Previously, lorengordon (Loren Gordon) wrote…</i></summary>
> We should have a discussion on whether to call this a .ps1 file, or .ps1.txt. The xml <powershell> tags make it invalid powershell...
</details>
Good point.  I was thinking of leaving the <powershell> tags in there since that will allow for the option of reading in the file when creating EC2 Windows image rather than parsing a string.  I agree that we probably should go with something .ps1.txt, although we could also go with another extension that reflects its use as a userdata script for AWS.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plus3it/watchmaker/12)*

**Comment by lorengordon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[watchmaker/static/shell/bootstrappers/windows-image-bootstrap.ps1, line 1 \[r1\]](https://reviewable.io:443/reviews/plus3it/watchmaker/12#-KJafHWYUOV0BEtS8uGV:-KJb1EshrVbpkPnPRWg6:1715291504) ([raw file](https://github.com/plus3it/watchmaker/blob/0075a34126491b863c9e0ebdf9a85ff6b45936c7/watchmaker/static/shell/bootstrappers/windows-image-bootstrap.ps1#L1)):*
<details><summary><i>Previously, KevinPlus3 (Kevin Hulsing) wrote…</i></summary>
> Good point.  I was thinking of leaving the <powershell> tags in there since that will allow for the option of reading in the file when creating EC2 Windows image rather than parsing a string.  I agree that we probably should go with something .ps1.txt, although we could also go with another extension that reflects its use as a userdata script for AWS.
</details>
After discussing, decided to remove the xml tags and leave it a .ps1 script.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plus3it/watchmaker/12)*

**Comment by lorengordon** [comment]
Per discussion, also need to rename the files to `watchmaker-bootstrap.<ext>`

<details><summary><i>Previously, lorengordon (Loren Gordon) wrote…</i></summary>
> This looks correct. There were 5 commits previously, now there are 4. The commit _message_ on the 4th commit is a little odd, though not unusual when squashing. You could use `git commit --amend` if you wanted to cleanup the message.
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/plus3it/watchmaker/12#-:-KJb1jLrZup259_W2wRJ:-703962246)*

**Comment by KevinPlus3** [comment]
Currently testing new changes before pushing up.

**Comment by lorengordon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[watchmaker/static/shell/bootstrappers/watchmaker-bootstrap.ps1, line 1 \[r1\]](https://reviewable.io:443/reviews/plus3it/watchmaker/12#-KJafHWYUOV0BEtS8uGV:-KJb8RYOYufwXExgj0XW:676834233) ([raw file](https://github.com/plus3it/watchmaker/blob/0075a34126491b863c9e0ebdf9a85ff6b45936c7/watchmaker/static/shell/bootstrappers/watchmaker-bootstrap.ps1#L1)):*
<details><summary><i>Previously, lorengordon (Loren Gordon) wrote…</i></summary>
> After discussing, decided to remove the xml tags and leave it a .ps1 script.
</details>
LGTM

---

*[watchmaker/static/shell/bootstrappers/watchmaker-bootstrap.py, line 1 \[r1\]](https://reviewable.io:443/reviews/plus3it/watchmaker/12#-KJaeip5mv7w6wg6SgE9:-KJb8WHxPxIfQHVZh5wK:676834233) ([raw file](https://github.com/plus3it/watchmaker/blob/0075a34126491b863c9e0ebdf9a85ff6b45936c7/watchmaker/static/shell/bootstrappers/watchmaker-bootstrap.py#L1)):*
<details><summary><i>Previously, lorengordon (Loren Gordon) wrote…</i></summary>
> This is a .py file, should this be `#!/usr/bin/env python`?
</details>
LGTM

---

*[watchmaker/static/shell/bootstrappers/watchmaker-bootstrap.py, line 3 \[r1\]](https://reviewable.io:443/reviews/plus3it/watchmaker/12#-KJaeyHayDnv7el8VKkw:-KJb8XUqp9rCp5sDd-Xh:676834233) ([raw file](https://github.com/plus3it/watchmaker/blob/0075a34126491b863c9e0ebdf9a85ff6b45936c7/watchmaker/static/shell/bootstrappers/watchmaker-bootstrap.py#L3)):*
<details><summary><i>Previously, lorengordon (Loren Gordon) wrote…</i></summary>
> Can you add a newline here? That little red mark at the end of the line is Github saying there is no newline character.
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plus3it/watchmaker/12)*

**Comment by lorengordon** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/plus3it/watchmaker/12)*

**Comment by lorengordon** [comment]
:ship:

**Pull request merged**
