### PR TITLE
Creates cross-platform executables using setup.py entry_points

### PR DESCRIPTION
**Pull request by lorengordon**
This change is [Reviewable](https://reviewable.io/reviews/plus3it/watchmaker/57)

### CODE REVIEW

**Comment by KevinPlus3** [comment]
Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[scripts/Watchmaker.py, line 0 \[r1\]](https://reviewable.io:443/reviews/plus3it/watchmaker/57#-KQRXAq7RwhqidJ7pmlf:-KQRXAq8XRtyBvl9HfxF:bfa1yxj) ([raw file](https://github.com/plus3it/watchmaker/blob/ae18ac5f82ef0eb7539ba1a326f98eef503151fa/scripts/Watchmaker.py#L0)):*
Does this eliminate the scripts directory?

---

*[src/watchmaker/__main__.py, line 2 \[r1\]](https://reviewable.io:443/reviews/plus3it/watchmaker/57#-KQRX0JgCF9E1tcazpuP:-KQRX0JgCF9E1tcazpuQ:bsatsch) ([raw file](https://github.com/plus3it/watchmaker/blob/ae18ac5f82ef0eb7539ba1a326f98eef503151fa/src/watchmaker/__main__.py#L2)):*
> ```Python
> """
> Entrypoint module, in case you use `python -mwatchmaker`.
> ```

Missing a space betweem -m and watchmaker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plus3it/watchmaker/57)*

**Comment by KevinPlus3** [comment]
Reviewed 4 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/plus3it/watchmaker/57)*

**Comment by KevinPlus3** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/plus3it/watchmaker/57)*

**Comment by lorengordon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[scripts/Watchmaker.py, line  \[r1\]](https://reviewable.io:443/reviews/plus3it/watchmaker/57#-KQRXAq7RwhqidJ7pmlf:-KQRZnQrcibN4PZr-ryE:bb77ucv) ([raw file](https://github.com/plus3it/watchmaker/blob/ae18ac5f82ef0eb7539ba1a326f98eef503151fa/scripts/Watchmaker.py#L)):*
<details><summary><i>Previously, KevinPlus3 (Kevin Hulsing) wrote…</i></summary>
> Does this eliminate the scripts directory?
</details>
Yep.

---

*[src/watchmaker/__main__.py, line 2 \[r1\]](https://reviewable.io:443/reviews/plus3it/watchmaker/57#-KQRX0JgCF9E1tcazpuP:-KQRZoTo0KucgiQrdlSy:bqmjwcz) ([raw file](https://github.com/plus3it/watchmaker/blob/ae18ac5f82ef0eb7539ba1a326f98eef503151fa/src/watchmaker/__main__.py#L2)):*
<details><summary><i>Previously, KevinPlus3 (Kevin Hulsing) wrote…</i></summary>
> Missing a space betweem -m and watchmaker.
</details>
Added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plus3it/watchmaker/57)*

**Comment by KevinPlus3** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/plus3it/watchmaker/57)*

**Pull request merged**
