### PR TITLE
Prepares watchmaker 0.10.0 release

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by lorengordon** [comment]
Will also be pulling in https://github.com/plus3it/ash-linux-formula/pull/250 once that's approved/merged. Just wanted to get a headstart on testing...

**Comment by lorengordon** [comment]
go codebuild go

**Comment by lorengordon** [comment]
go codebuild go

**Comment by YakDriver** [comment]
BadStatusLine exception seems to have been transitory AWS anomaly.

**Comment by lorengordon** [comment]
go codebuild go

**Pull request merged**
