### PR TITLE
Added Info for Azure Usage

### PR DESCRIPTION
**Pull request by KevinPlus3**
Added brief information in Usage documentation on using Custom Script Extension to run bash/PowerShell scripts for Watchmaker on an Azure virtual machine.

### CODE REVIEW

**Comment by eemperor** [comment]
@KevinPlus3 The block of text was inserted in between the heading `watchmaker as EC2 userdata` and it's subheading `Linux`.  Should be good once you move it outside in its own section.

**Comment by KevinPlus3** [comment]
Done.  Good catch.  I had difficulty deciding whether or should immediately follow the EC2 section or if I should put it after the templates.  I could fall either way since CloudFormation is an AWS thing and makes sense to follow the EC2 section, but on the other hand the use of scripts (for Linux and Windows) makes following immediately with the Custom Script Extension a good choice as well.

**Comment by lorengordon** [comment]
I think we should add sections, `watchmaker in AWS` and `watchmaker in Azure` (at the same level as `watchmaker from the CLI`), and make the related sections sub-headings within those.

**Comment by KevinPlus3** [comment]
Sounds good. Will work on that.

**Comment by lorengordon** [comment]
@KevinPlus3 any more changes expected?

**Comment by KevinPlus3** [comment]
Nope.  It is not as extensive as AWS section but I think Microsoft does a good job with documenting how to use it further.  If someone brings up expanding on it (possibly by adding a Resource Management Template like Eric experimented with), then maybe we can do that at a later time.

**Pull request merged**
